- name: '[KVM] | Install qemu-kvm'
  package:
    name: qemu-kvm
    state: present

- name: '[KVM] | Install nfs-kernel-server'
  package:
    name: nfs-kernel-server
    state: present

- name: '[KVM] | Install libvirt-clients'
  package:
    name:  libvirt-clients
    state: present

- name: '[KVM] | Install libvirt-daemon-system'
  package:
    name: libvirt-daemon-system
    state: present

- name: '[KVM] | Install python-libvirt'
  package:
    name: python-libvirt
    state: present

- name: '[NFS] | Install nfs-kernel-server'
  package:
    name: nfs-kernel-server
    state: present

- name: 'Virt | Define VM'
  virt:
    name: alpha
    command: define


- name: '[Run Vm]'
  virt:
    name: alpha
    state: running





