Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.box = "debian/stretch64"
        config.vm.synced_folder ".", "/vagrant",
            type: "nfs",
              linux__nfs_options: ['rw','no_subtree_check','all_squash','async']
        config.vm.define "node-#{i}" do |node|
            node.vm.provision "ansible" do |ansible|
                ansible.limit = "all"
                ansible.playbook = "playbook.yml"
            end
        end
    end
end