Vagrant.configure("2") do |config|
    (1..3).each do |i|
        config.vm.box = "debian/stretch64"
        config.vm.define "node-#{i}" do |node|
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "playbook.yml"
            end
        end
    end
end