- name: '[Certbot] | Install'
  package:
    name: certbot
    state: latest

- name: '[Nginx] | Install'
  package:
    name: nginx
    state: latest

- name: '[Nginx] | Configure'
  copy:
    src: '../nginx/'
    dest: '/etc/nginx/sites-available'

- name: '[Nginx] | Reload config'
  command: 'nginx -s reload'
  changed_when: False

- name: '[Ansible] | Install'
  package:
    name: ansible
    state: latest

- name: '[Vagrant] | Install'
  package:
    name: vagrant
    state: latest

- name: '[Vagrant] | Use KVM'
  command: 'vagrant plugin install vagrant-libvirt'

- name: '[Vagrant] | Configure'
  copy:
    src: '../vagrant/'
    dest: '/var/vagrant-nfs/'

- name: '[Vagrant] | Create VMs'
  command: 'vagrant up'
  environment:
    VAGRANT_DEFAULT_PROVIDER: libvirt
  args:
    chdir: '/var/vagrant-nfs'


