- name: '[Certbot] | Install'
  package:
    name: certbot
    state: latest

- name: '[Nginx] | Install'
  package:
    name: nginx
    state: latest

- name: '[Vagrant] | Install'
  package:
    name: vagrant
    state: latest

- name: '[Vagrant] | Configure'
  copy:
    src: '../vagrant/'
    dest: '/vagrant/'

- name: '[Vagrant] | Create VMs'
  command: 'vagrant up'
  args:
    chdir: '/vagrant'


