- name: '[Certbot] | Install'
  package:
    name: certbot
    state: latest

- name: '[Nginx] | Install'
  package:
    name: nginx
    state: latest

- name: '[Vagrant] | Install'
  package:
    name: vagrant
    state: latest

