- name: '[Certbot] | Install'
  package:
    name: certbot
    state: present

- name: '[Nginx] | Install'
  package:
    name: nginx
    state: present

- name: '[Nginx] | Configure'
  copy:
    src: '../nginx/'
    dest: '/etc/nginx/sites-available'

- name: '[Nginx] | Reload config'
  command: 'nginx -s reload'
  changed_when: False

- name: '[Ansible] | Install'
  package:
    name: ansible
    state: latest



