- name: '[VirtualBox] | Add apt-key'
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    state: present

- name: '[VirtualBox] | Add repository'
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{distro.stdout}} contrib'
    state: present
    update_cache: yes

- name: '[VirtualBox] | Install'
  package:
    name: virtualbox-5.1
    state: present